name: S3 Sync - Production

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.5.1
      with:
        node-version: '15'

    - name: Display structure of downloaded files
      run: ls -R

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: web-app-dist
        path: './'

  deploy_to_production:
    name: Deploy to S3 Production
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download landing page artifact
      uses: actions/download-artifact@v2
      with:
        name: web-app-dist
        path: ./aaa

    - name: Display structure of downloaded files
      run: ls -R
      
    - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Sync files to S3 bucket
        run: aws s3 cp aaa s3://testgithubvlabs/test --recursive
    
