
on:
  release:
  
name: Check event

jobs:
  print-event-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print GitHub Event
        run: |
          echo "GitHub Event:"
          cat $GITHUB_EVENT_PATH | jq
