
on:
  release:
  
name: Check event

jobs:
  print-event-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          ref: ${{ github.event.release.tag_name }}
      - name: Print GitHub Event
        run: |
          ls

      - name: Print GitHub Event
        run: |
          echo "GitHub Event:"
          cat $GITHUB_EVENT_PATH | jq
          echo "===============================\n"
          echo "Release Tag Name: ${{ github.event.release.tag_name }}"
