on:
  workflow_dispatch:
  
name: Check User Team Membership

jobs:
  check_team_membership:
    runs-on: ubuntu-latest

    steps:
      - name: Check User Team Membership
        run: |
          curl -s -H "Authorization: Bearer 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"  https://api.github.com/orgs/vktestorg/teams/test1/memberships/vikramk20
          
