on:
  workflow_dispatch:
  
name: Check User Team Membership

on:
  workflow_run:
    workflows: ["YourWorkflowName"]  # Replace with the name of your workflow that triggers this check
    types:
      - completed

jobs:
  check_team_membership:
    runs-on: ubuntu-latest

    steps:
      - name: Check User Team Membership
        run: |
          # Replace with your GitHub username
          USERNAME=vikramk20
          # Replace with your organization name
          ORG=vktest
          # Replace with the name of the team you want to check membership for
          TEAM=test1
          # Replace with your Personal Access Token (PAT)
          PAT=${{ secrets.VK_TOK }}

          MEMBERSHIP=$(curl -s -H "Authorization: token $PAT" "https://api.github.com/orgs/$ORG/teams/$TEAM/memberships/$USERNAME")

          if [[ $MEMBERSHIP == *"\"state\": \"active\""* ]]; then
              echo "User $USERNAME is a member of team $TEAM in organization $ORG."
          else
              echo "User $USERNAME is not a member of team $TEAM in organization $ORG."
          fi
