on:
  workflow_dispatch:
jobs:
  runs-on: ubuntu-latest
  name: Action to update the member's list
  steps:
    - name: Member List
      id: list-members
      uses: RITct/members-list-action@main
      with:
        org-name: vktestorg
        file-path: 'members.json'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
