name: Get Release Author

on:
  release:
    types:
      - published

jobs:
  check-user:
    runs-on: ubuntu-latest

    steps:
      - name: Check User Team Membership
        run: |
          # Replace with your GitHub username
          USERNAME=vikramk20
          # Replace with your organization name
          ORG=vktestorg
          # Replace with the name of the team you want to check membership for
          TEAM=test1
          # Replace with your Personal Access Token (PAT)
          PAT=${{ secrets.GITHUB_TOKEN }}

          MEMBERSHIP=$(curl -s -H "Authorization: token $PAT" "https://api.github.com/orgs/$ORG/teams/$TEAM/memberships/$USERNAME")

          echo MEMBERSHIP, $MEMBERSHIP
  
