name: Get Release Author

on:
  workflow_dispatch:

jobs:
  check-member:
    runs-on: ubuntu-latest
    name: Check if an user exists
    steps:
      -name: build
      id: get-members
      uses: garnertb/get-team-members@v1
      with:
        org: vktestorg
        team_slug: test
        token: ${{ secrets.GITHUB_TOKEN }}
      
      -run: |
        "echo ${{ steps.get-members.outputs.members }}"
        shell: bash
