name: Get Release Author

on:
  release:
    types:
      - published

jobs:
  check-user:
    name: Team affiliation
    runs-on: ubuntu-latest
    permissions:
      repository-projects: read
    steps:
      - name: Check user for team affiliation
        uses: tspascoal/get-user-teams-membership@v2
        id: teamAffiliation
        
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.actor }}
          team: test1
      - name: Stop workflow if user is no member
        if: ${{ steps.teamAffiliation.outputs.isTeamMember == false }}
        run: |
          echo "You have no rights to trigger this job."
          exit 1
