name: Get Release Author

on:
  release:
    types:
      - published

jobs:
  get_release_author:
    runs-on: ubuntu-latest

    steps:
      - name: Get Release Author
        run: echo ${{ toJson(github.event) }} | jq .
