on:
  workflow_dispatch:
  
name: Check User Team Membership

jobs:
  check_team_membership:
    runs-on: ubuntu-latest

    steps:
      - name: Check User Team Membership
        run: |
          PAT=${{ secrets.VK_PAT1 }}
          curl -s -H "Authorization: Bearer $PAT"  https://api.github.com/orgs/vktestorg/teams/test1/memberships/vikramk20
          
