name: main
on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: token
        env:
            GH_TOKEN: ${{ github.token }}
        run: gh issue create --title "My new issue" --body "Here are more details."
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: vikramk20
      - name: Deploy to production
        run: echo deploying
