name: Get Release Author

on:
  release:
    types:
      - published

jobs:
  get_release_author:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Release Author
        run: echo Release Author, ${{ github.event.release.author.login }}
